import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { PageLayout } from "@/components/layout/page-layout";
import { DataTable } from "@/components/ui/data-table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FormDialog } from "@/components/ui/form-dialog";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { StatusBadge } from "@/components/ui/status-badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import {
  useListRecurringProfiles,
  useCreateRecurringProfile,
  useDeleteRecurringProfile,
  usePauseRecurringProfile,
  useRunRecurringProfileNow,
  useListRecurringProfileChildren,
  getListRecurringProfilesQueryKey,
  getListRecurringProfileChildrenQueryKey,
  useListCustomers,
} from "@workspace/api-client-react";
import type { RecurringProfile, RecurringProfileInput } from "@workspace/api-client-react";
import { formatCurrency, formatDate } from "@/lib/utils";
import { Play, Pause, History, Trash2, Zap } from "lucide-react";

const FREQUENCIES = ["daily", "weekly", "biweekly", "monthly", "quarterly", "yearly", "custom"];

type FormState = {
  name: string;
  customerId: string;
  frequency: string;
  customDays: string;
  subtotal: string;
  taxAmount: string;
  dueInDays: string;
  startDate: string;
};

const today = new Date().toISOString().slice(0, 10);

const EMPTY: FormState = {
  name: "",
  customerId: "",
  frequency: "monthly",
  customDays: "",
  subtotal: "",
  taxAmount: "",
  dueInDays: "15",
  startDate: today,
};

// Schedule-health hint (better-than-Zoho §8.3): a human relative label + tone.
function relativeRun(iso: string): { label: string; tone: string } {
  const diffMs = new Date(iso).getTime() - Date.now();
  const days = Math.round(diffMs / 86_400_000);
  if (days < 0) return { label: `overdue ${-days}d`, tone: "text-amber-600" };
  if (days === 0) return { label: "due today", tone: "text-blue-600" };
  if (days === 1) return { label: "in 1 day", tone: "text-muted-foreground" };
  return { label: `in ${days} days`, tone: "text-muted-foreground" };
}

function ChildrenDialog({ profile, onClose }: { profile: RecurringProfile | null; onClose: () => void }) {
  const { data: children, isLoading } = useListRecurringProfileChildren(profile?.id ?? 0, {
    query: {
      enabled: !!profile,
      queryKey: getListRecurringProfileChildrenQueryKey(profile?.id ?? 0),
    },
  });
  return (
    <Dialog open={!!profile} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Run history — {profile?.name}</DialogTitle>
          <DialogDescription>Invoices generated by this recurring profile.</DialogDescription>
        </DialogHeader>
        <DataTable
          columns={[
            { header: "Invoice #", cell: (c) => <span className="font-mono text-xs">{c.entityNumber ?? "—"}</span> },
            { header: "Amount", cell: (c) => <span className="font-medium">{formatCurrency(c.amount)}</span> },
            { header: "Generated", cell: (c) => formatDate(c.generatedAt) },
            { header: "Status", cell: (c) => <StatusBadge status={c.status} /> },
          ]}
          data={children}
          isLoading={isLoading}
          emptyTitle="No invoices generated yet"
          emptyDescription="Use “Run now” or wait for the next scheduled run."
        />
      </DialogContent>
    </Dialog>
  );
}

export function RecurringProfilesPage() {
  const qc = useQueryClient();
  const { data: profiles, isLoading } = useListRecurringProfiles();
  const { data: customers } = useListCustomers();

  const [formOpen, setFormOpen] = useState(false);
  const [deleting, setDeleting] = useState<RecurringProfile | null>(null);
  const [viewing, setViewing] = useState<RecurringProfile | null>(null);
  const [form, setForm] = useState<FormState>(EMPTY);

  const invalidate = () => qc.invalidateQueries({ queryKey: getListRecurringProfilesQueryKey() });

  const createMutation = useCreateRecurringProfile({
    mutation: { onSuccess: () => { invalidate(); setFormOpen(false); } },
  });
  const deleteMutation = useDeleteRecurringProfile({
    mutation: { onSuccess: () => { invalidate(); setDeleting(null); } },
  });
  const pauseMutation = usePauseRecurringProfile({ mutation: { onSuccess: invalidate } });
  const runNowMutation = useRunRecurringProfileNow({
    mutation: {
      onSuccess: (_data, vars) => {
        invalidate();
        qc.invalidateQueries({ queryKey: getListRecurringProfileChildrenQueryKey(vars.id) });
      },
    },
  });

  function set(field: keyof FormState, value: string) {
    setForm((f) => ({ ...f, [field]: value }));
  }

  function openCreate() {
    setForm(EMPTY);
    setFormOpen(true);
  }

  function handleSubmit() {
    if (!form.name.trim() || !form.customerId || !form.subtotal) return;
    const data: RecurringProfileInput = {
      name: form.name,
      customerId: Number(form.customerId),
      frequency: form.frequency,
      customDays: form.frequency === "custom" && form.customDays ? Number(form.customDays) : undefined,
      subtotal: parseFloat(form.subtotal),
      taxAmount: form.taxAmount ? parseFloat(form.taxAmount) : undefined,
      dueInDays: form.dueInDays ? Number(form.dueInDays) : undefined,
      startDate: form.startDate || undefined,
    };
    createMutation.mutate({ data });
  }

  const columns = [
    { header: "Name", accessorKey: "name" as const },
    {
      header: "Customer",
      cell: (p: RecurringProfile) =>
        p.customerName ? <span className="text-sm">{p.customerName}</span> : <span className="text-muted-foreground">—</span>,
    },
    { header: "Frequency", cell: (p: RecurringProfile) => <span className="capitalize">{p.frequency}</span> },
    {
      header: "Amount",
      cell: (p: RecurringProfile) => <span className="font-medium">{formatCurrency(p.templateData.total)}</span>,
    },
    {
      header: "Next run",
      cell: (p: RecurringProfile) => {
        if (p.status !== "active") return <span className="text-muted-foreground">—</span>;
        const rel = relativeRun(p.nextRunAt);
        return (
          <div className="flex flex-col">
            <span className="text-sm">{formatDate(p.nextRunAt)}</span>
            <span className={`text-xs ${rel.tone}`}>{rel.label}</span>
          </div>
        );
      },
    },
    {
      header: "Generated",
      cell: (p: RecurringProfile) => <span className="tabular-nums">{p.childCount}</span>,
    },
    { header: "Status", cell: (p: RecurringProfile) => <StatusBadge status={p.status} /> },
    {
      header: "",
      cell: (p: RecurringProfile) => (
        <div className="flex items-center justify-end gap-1">
          <Button
            variant="ghost"
            size="sm"
            className="h-7 gap-1 px-2 text-xs"
            disabled={runNowMutation.isPending}
            onClick={() => runNowMutation.mutate({ id: p.id })}
            title="Generate an invoice now"
          >
            <Zap className="h-3.5 w-3.5" /> Run
          </Button>
          {p.status !== "expired" && (
            <Button
              variant="ghost"
              size="sm"
              className="h-7 w-7 p-0 text-muted-foreground"
              onClick={() => pauseMutation.mutate({ id: p.id })}
              title={p.status === "active" ? "Pause" : "Resume"}
            >
              {p.status === "active" ? <Pause className="h-3.5 w-3.5" /> : <Play className="h-3.5 w-3.5" />}
            </Button>
          )}
          <Button
            variant="ghost"
            size="sm"
            className="h-7 w-7 p-0 text-muted-foreground"
            onClick={() => setViewing(p)}
            title="Run history"
          >
            <History className="h-3.5 w-3.5" />
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="h-7 w-7 p-0 text-muted-foreground hover:text-destructive"
            onClick={() => setDeleting(p)}
            title="Delete"
          >
            <Trash2 className="h-3.5 w-3.5" />
          </Button>
        </div>
      ),
    },
  ];

  return (
    <PageLayout
      title="Recurring Profiles"
      description="Templates that auto-generate invoices on a schedule. The engine runs continuously; “Run now” generates one immediately."
      actionLabel="New Recurring Profile"
      onAction={openCreate}
    >
      <DataTable
        columns={columns}
        data={profiles}
        isLoading={isLoading}
        emptyTitle="No recurring profiles"
        emptyDescription="Create a profile to auto-generate invoices for a customer on a cadence."
      />

      <FormDialog
        open={formOpen}
        onOpenChange={setFormOpen}
        title="New Recurring Profile"
        description="The engine mints a draft invoice each cycle from this template."
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
        submitLabel="Create Profile"
        size="md"
      >
        <div className="grid grid-cols-2 gap-4">
          <div className="col-span-2 space-y-1.5">
            <Label>Name *</Label>
            <Input value={form.name} onChange={(e) => set("name", e.target.value)} placeholder="e.g. Monthly retainer — Acme" />
          </div>
          <div className="col-span-2 space-y-1.5">
            <Label>Customer *</Label>
            <Select value={form.customerId} onValueChange={(v) => set("customerId", v)}>
              <SelectTrigger>
                <SelectValue placeholder="Select a customer" />
              </SelectTrigger>
              <SelectContent>
                {(customers ?? []).map((c) => (
                  <SelectItem key={c.id} value={String(c.id)}>
                    {c.name}{c.company ? ` — ${c.company}` : ""}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1.5">
            <Label>Frequency *</Label>
            <Select value={form.frequency} onValueChange={(v) => set("frequency", v)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {FREQUENCIES.map((f) => (
                  <SelectItem key={f} value={f} className="capitalize">{f}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          {form.frequency === "custom" ? (
            <div className="space-y-1.5">
              <Label>Every N days *</Label>
              <Input type="number" value={form.customDays} onChange={(e) => set("customDays", e.target.value)} placeholder="e.g. 45" />
            </div>
          ) : (
            <div className="space-y-1.5">
              <Label>Start date</Label>
              <Input type="date" value={form.startDate} onChange={(e) => set("startDate", e.target.value)} />
            </div>
          )}
          {form.frequency === "custom" && (
            <div className="space-y-1.5">
              <Label>Start date</Label>
              <Input type="date" value={form.startDate} onChange={(e) => set("startDate", e.target.value)} />
            </div>
          )}
          <div className="space-y-1.5">
            <Label>Subtotal *</Label>
            <Input type="number" value={form.subtotal} onChange={(e) => set("subtotal", e.target.value)} placeholder="0.00" />
          </div>
          <div className="space-y-1.5">
            <Label>Tax amount</Label>
            <Input type="number" value={form.taxAmount} onChange={(e) => set("taxAmount", e.target.value)} placeholder="0.00" />
          </div>
          <div className="space-y-1.5">
            <Label>Due in (days)</Label>
            <Input type="number" value={form.dueInDays} onChange={(e) => set("dueInDays", e.target.value)} placeholder="15" />
          </div>
        </div>
      </FormDialog>

      <ConfirmDialog
        open={!!deleting}
        onOpenChange={(o) => !o && setDeleting(null)}
        title="Delete Recurring Profile"
        description={`Delete "${deleting?.name}"? Generated invoices are kept; only the profile is removed.`}
        onConfirm={() => deleting && deleteMutation.mutate({ id: deleting.id })}
        isLoading={deleteMutation.isPending}
      />

      <ChildrenDialog profile={viewing} onClose={() => setViewing(null)} />
    </PageLayout>
  );
}
